# Generated by Django 5.2.6 on 2025-11-27 11:00

from django.db import migrations


def add_developer_role(apps, schema_editor):
    """添加 Developer 角色"""
    Role = apps.get_model("TeamManagement", "Role")

    # 创建 Developer 角色（如果不存在）
    Role.objects.get_or_create(
        name="Developer", defaults={"description": "开发人员，负责项目开发和代码实现"}
    )


def remove_developer_role(apps, schema_editor):
    """移除 Developer 角色（回滚操作）"""
    Role = apps.get_model("TeamManagement", "Role")
    Role.objects.filter(name="Developer").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("TeamManagement", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_developer_role, remove_developer_role),
    ]
