# Generated by Django 5.2.8 on 2025-11-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Visualization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sprint",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-id"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterField(
            model_name="sprint",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Sprint Name"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="total_story_points",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Story Points"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed At"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="Visualization.sprint",
                verbose_name="Sprint",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(default=1, verbose_name="Story Points"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Task Title"),
        ),
    ]
