# Generated by Django 5.2.6 on 2025-11-01 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                ("file", models.FileField(upload_to="documents/", verbose_name="文件")),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=50, verbose_name="角色")),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="加入日期"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="预计工时",
                    ),
                ),
                (
                    "consumed_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="消耗工时",
                    ),
                ),
                (
                    "remaining_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="剩余工时"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="ProjectManagement.teammember",
                        verbose_name="指派给",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="项目编号"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                ("planned_start_date", models.DateField(verbose_name="计划开始日期")),
                ("planned_end_date", models.DateField(verbose_name="计划完成日期")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际开始日期"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际完成日期"
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="预计工时",
                    ),
                ),
                (
                    "consumed_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="消耗工时",
                    ),
                ),
                (
                    "remaining_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="剩余工时"
                    ),
                ),
                (
                    "available_workdays",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="可用工日",
                    ),
                ),
                (
                    "available_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="可用工时"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "规划中"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("suspended", "已暂停"),
                            ("cancelled", "已取消"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="ProjectManagement.document",
                        verbose_name="文档库",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        related_name="projects",
                        to="ProjectManagement.teammember",
                        verbose_name="团队成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
    ]
