# Generated by Django 5.2.6 on 2025-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="ProjectManagement.teammember",
                verbose_name="团队成员",
            ),
        ),
    ]
