# Generated by Django 5.2.6 on 2025-11-01 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManagement", "0002_alter_project_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="available_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="可用工时",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="available_workdays",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="可用工日",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="remaining_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="剩余工时",
            ),
        ),
    ]
