# Generated by Django 5.2.6 on 2025-11-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManagement", "0003_alter_project_available_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="ProjectManagement.project",
                verbose_name="所属项目",
            ),
            preserve_default=False,
        ),
    ]
