# Generated by Django 5.2.6 on 2025-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManagement", "0004_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "未开始"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("suspended", "已暂停"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
