# Generated by Django 5.2.6 on 2025-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManagement", "0005_remove_task_completed_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="实际完成日期"),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="实际开始日期"),
        ),
        migrations.AddField(
            model_name="task",
            name="planned_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="计划开始日期"),
        ),
    ]
